name: Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        run: |
          rustup default 1.87
          rustup component add clippy
          rustc --version

      - uses: actions/checkout@v6

      - name: Run linter
        run: cargo clippy
